//! TypeScript type generator for whatsapp-rust types.
//!
//! Parses Rust source files with `syn`, finds structs/enums with `#[derive(Serialize)]`,
//! and generates TypeScript interfaces/types.
//!
//! Usage: bun run gen:types (outputs to ../src/generated_types.rs)

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use syn::{Attribute, Fields, GenericArgument, Item, PathArguments, Type, TypePath};
use walkdir::WalkDir;

/// Find whatsapp-rust source dir from Cargo's git cache by parsing Cargo.lock.
/// Falls back to `../../whatsapp-rust/` for local development.
fn find_whatsapp_rust_root() -> PathBuf {
    // Try to find it in Cargo's git checkout cache
    let lock_path = Path::new("../Cargo.lock");
    if let Ok(lock_content) = std::fs::read_to_string(lock_path) {
        // Find commit hash from: source = "git+https://...whatsapp-rust?...#<hash>"
        for line in lock_content.lines() {
            if line.contains("whatsapp-rust")
                && line.contains("#")
                && let Some(hash_start) = line.rfind('#')
            {
                let full_hash = line[hash_start + 1..].trim_end_matches('"');
                // Cargo checkouts use first 7 chars of the commit hash as dir name
                let short_hash = &full_hash[..7];

                // Search for the checkout dir in ~/.cargo/git/checkouts/
                let cargo_home = std::env::var("CARGO_HOME").unwrap_or_else(|_| {
                    let home = std::env::var("HOME").expect("HOME not set");
                    format!("{}/.cargo", home)
                });
                let checkouts = PathBuf::from(&cargo_home).join("git/checkouts");

                if let Ok(entries) = std::fs::read_dir(&checkouts) {
                    for entry in entries.flatten() {
                        let name = entry.file_name();
                        if name.to_string_lossy().starts_with("whatsapp-rust-") {
                            let candidate = entry.path().join(short_hash);
                            if candidate.exists() {
                                eprintln!("Using Cargo git cache: {}", candidate.display());
                                return candidate;
                            }
                        }
                    }
                }
            }
        }
    }

    // Fallback to local clone
    let fallback = PathBuf::from("../../whatsapp-rust");
    eprintln!("Using local path: {}", fallback.display());
    fallback
}

fn main() {
    let root = find_whatsapp_rust_root();
    let wacore_dir = root.join("wacore/src");
    let src_dir = root.join("src");

    let mut all_types = BTreeMap::new();

    // Parse wacore types
    for entry in WalkDir::new(wacore_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "rs"))
    {
        parse_file(entry.path(), &mut all_types);
    }

    // Parse whatsapp-rust feature types
    let feature_dirs = ["features", "types"];
    for dir in feature_dirs {
        let path = src_dir.join(dir);
        if path.exists() {
            for entry in WalkDir::new(&path)
                .into_iter()
                .filter_map(|e| e.ok())
                .filter(|e| e.path().extension().is_some_and(|ext| ext == "rs"))
            {
                parse_file(entry.path(), &mut all_types);
            }
        }
    }

    // Also parse send.rs for SendOptions/RevokeType
    parse_file(&src_dir.join("send.rs"), &mut all_types);

    // Build TypeScript content
    let mut ts = String::new();

    // Jid is defined in wacore-binary with cfg_attr(feature = "serde"), so the codegen
    // can't discover it automatically. Hardcoded to match serde output.
    ts.push_str("/** WhatsApp JID (Jabber ID) — identifies a user, group, or device. */\n");
    ts.push_str("export interface Jid {\n");
    ts.push_str("  user: string;\n");
    ts.push_str("  server: string;\n");
    ts.push_str("  agent: number;\n");
    ts.push_str("  device: number;\n");
    ts.push_str("  integrator: number;\n");
    ts.push_str("}\n");

    for (name, ts_type) in &all_types {
        ts.push('\n');
        ts.push_str(&ts_type.to_typescript(name));
        ts.push('\n');
    }

    // Output as a Rust source file with typescript_custom_section
    println!("//! Auto-generated TypeScript type declarations for wasm-bindgen.");
    println!("//! Generated by: bun run gen:types");
    println!("//! DO NOT EDIT — re-run gen:types to regenerate.");
    println!();
    println!("use wasm_bindgen::prelude::*;");
    println!();

    // Pick raw string delimiter that doesn't conflict with content
    let delim = if ts.contains("\"#") { "##" } else { "#" };

    println!("#[wasm_bindgen(typescript_custom_section)]");
    println!("const _TS_GENERATED_TYPES: &str = r{delim}\"");
    print!("{ts}");
    println!("\"{delim};");
}

#[derive(Debug)]
enum TsTypeDef {
    Interface {
        fields: Vec<TsField>,
        doc: Option<String>,
    },
    Enum {
        variants: Vec<TsEnumVariant>,
        doc: Option<String>,
    },
    StringEnum {
        variants: Vec<(String, String)>, // (name, value)
        /// `true` when the enum has a `#[wire_fallback]` variant (or
        /// equivalent). The TS type widens to include `string` so unknown
        /// wire tags don't fail consumer type checks.
        has_fallback: bool,
        doc: Option<String>,
    },
    /// Numeric enum (`#[wire(kind = "int")]`) — discriminator is `i32`.
    /// Renders as `export type X = number;` plus a doc comment listing the
    /// known codes for human reference.
    IntEnum {
        codes: Vec<(String, String)>, // (variant_name, numeric_literal)
        doc: Option<String>,
    },
}

#[derive(Debug)]
struct TsField {
    name: String,
    ts_type: String,
    optional: bool,
    doc: Option<String>,
}

#[derive(Debug)]
enum TsEnumVariant {
    /// Unit variant. `wire` is the explicit discriminator string (from
    /// `#[wire = "..."]`); empty when the variant should fall back to
    /// `to_snake_case(name)`.
    Unit { name: String, wire: String },
    Tuple {
        name: String,
        wire: String,
        inner: String,
    },
    Struct {
        name: String,
        wire: String,
        fields: Vec<TsField>,
    },
    /// `#[wire_fallback]` catch-all for tagged-payload enums — emits
    /// `{ type: string; tag: string }` so any unknown discriminator still
    /// satisfies the union.
    Fallback,
}

impl TsTypeDef {
    fn to_typescript(&self, name: &str) -> String {
        match self {
            TsTypeDef::Interface { fields, doc } => {
                let mut out = String::new();
                if let Some(d) = doc {
                    out.push_str(&format!("/** {} */\n", d.trim()));
                }
                out.push_str(&format!("export interface {} {{\n", name));
                for f in fields {
                    if let Some(d) = &f.doc {
                        out.push_str(&format!("  /** {} */\n", d.trim()));
                    }
                    let opt = if f.optional { "?" } else { "" };
                    out.push_str(&format!("  {}{}: {};\n", f.name, opt, f.ts_type));
                }
                out.push('}');
                out
            }
            TsTypeDef::Enum { variants, doc } => {
                let mut out = String::new();
                if let Some(d) = doc {
                    out.push_str(&format!("/** {} */\n", d.trim()));
                }
                out.push_str(&format!("export type {} =\n", name));
                let parts: Vec<String> = variants
                    .iter()
                    .map(|v| match v {
                        TsEnumVariant::Unit { name, wire } => {
                            let tag = if wire.is_empty() { to_snake_case(name) } else { wire.clone() };
                            format!("  | {{ type: \"{}\" }}", tag)
                        }
                        TsEnumVariant::Tuple { name, wire, inner } => {
                            let tag = if wire.is_empty() { to_snake_case(name) } else { wire.clone() };
                            format!("  | {{ type: \"{}\"; data: {} }}", tag, inner)
                        }
                        TsEnumVariant::Struct { name, wire, fields } => {
                            let tag = if wire.is_empty() { to_snake_case(name) } else { wire.clone() };
                            let fs: Vec<String> = fields
                                .iter()
                                .map(|f| {
                                    let opt = if f.optional { "?" } else { "" };
                                    format!("{}{}: {}", f.name, opt, f.ts_type)
                                })
                                .collect();
                            if fs.is_empty() {
                                format!("  | {{ type: \"{}\" }}", tag)
                            } else {
                                format!("  | {{ type: \"{}\"; {} }}", tag, fs.join("; "))
                            }
                        }
                        TsEnumVariant::Fallback => {
                            // Catch-all: any other discriminator string + the
                            // captured tag. Mirrors `#[wire_fallback]` Unknown
                            // { tag: String } on the rust side.
                            "  | { type: string; tag: string }".to_string()
                        }
                    })
                    .collect();
                out.push_str(&parts.join("\n"));
                out.push(';');
                out
            }
            TsTypeDef::StringEnum { variants, has_fallback, doc } => {
                let mut out = String::new();
                if let Some(d) = doc {
                    out.push_str(&format!("/** {} */\n", d.trim()));
                }
                let mut parts: Vec<String> =
                    variants.iter().map(|(_, v)| format!("\"{}\"", v)).collect();
                if *has_fallback {
                    parts.push("string".to_string());
                }
                out.push_str(&format!("export type {} = {};", name, parts.join(" | ")));
                out
            }
            TsTypeDef::IntEnum { codes, doc } => {
                let mut out = String::new();
                let combined_doc = match doc {
                    Some(d) => d.clone(),
                    None => String::new(),
                };
                let codes_doc = codes
                    .iter()
                    .map(|(n, v)| format!("{}={}", v, n))
                    .collect::<Vec<_>>()
                    .join(", ");
                let final_doc = if combined_doc.is_empty() {
                    format!("Wire codes: {}", codes_doc)
                } else {
                    format!("{} Wire codes: {}", combined_doc.trim(), codes_doc)
                };
                out.push_str(&format!("/** {} */\n", final_doc));
                out.push_str(&format!("export type {} = number;", name));
                out
            }
        }
    }
}

fn parse_file(path: &Path, types: &mut BTreeMap<String, TsTypeDef>) {
    let Ok(content) = std::fs::read_to_string(path) else {
        return;
    };
    let Ok(file) = syn::parse_file(&content) else {
        return;
    };

    for item in &file.items {
        match item {
            Item::Struct(s) => {
                if has_serde_derive(&s.attrs) && is_pub(&s.vis) {
                    let name = s.ident.to_string();

                    // Skip types that are already generated by Tsify derives in
                    // result_types.rs — avoids duplicate export conflicts.
                    const TSIFY_STRUCTS: &[&str] = &[
                        "BusinessProfile",
                        "BusinessCategory",
                        "BusinessHours",
                        "BusinessHoursConfig",
                        "GroupMetadataParticipant",
                        "MembershipRequest",
                    ];
                    if TSIFY_STRUCTS.contains(&name.as_str()) {
                        continue;
                    }

                    let doc = extract_doc(&s.attrs);
                    let fields = match &s.fields {
                        Fields::Named(named) => named
                            .named
                            .iter()
                            .filter(|f| is_pub(&f.vis))
                            .map(|f| {
                                let field_name =
                                    f.ident.as_ref().unwrap().to_string().replace("r#", "");
                                let (ts_type, optional) = rust_type_to_ts(&f.ty);
                                let serde_name = get_serde_rename(f);
                                TsField {
                                    name: serde_name.unwrap_or(field_name),
                                    ts_type,
                                    optional,
                                    doc: extract_doc(&f.attrs),
                                }
                            })
                            .collect(),
                        _ => Vec::new(),
                    };
                    if !fields.is_empty() {
                        types.insert(name, TsTypeDef::Interface { fields, doc });
                    }
                }
            }
            Item::Enum(e) => {
                if !is_pub(&e.vis) {
                    continue;
                }

                // Skip types already generated by Tsify in result_types.rs
                let ename = e.ident.to_string();
                if TSIFY_GENERATED.contains(&ename.as_str()) {
                    continue;
                }

                // Sibling `<Name>Tag` enums auto-generated by `WireEnum`'s
                // tagged mode are an internal parser-dispatch helper — they
                // exist only after macro expansion (not in source), so the
                // `syn`-based codegen never sees them. No filter needed here;
                // documenting for the next reader.

                let name = e.ident.to_string();

                // Recognize `#[derive(WireEnum)]` (the unified successor to
                // `#[derive(StringEnum)]` plus the hand-written `impl
                // Serialize` blocks from before whatsapp-rust PR #567).
                // Three modes inferred from enum-level attributes:
                //   - unit-string  (default — drop-in `StringEnum` replacement)
                //   - tagged       (`#[wire(tag = "type")]` — payload variants)
                //   - int          (`#[wire(kind = "int")]`)
                if has_wire_enum_derive(&e.attrs) {
                    match wire_enum_kind(&e.attrs) {
                        WireEnumKind::Int => {
                            let codes: Vec<(String, String)> = e
                                .variants
                                .iter()
                                .filter(|v| !is_wire_fallback(&v.attrs))
                                .map(|v| (v.ident.to_string(), get_wire_attr_lit(&v.attrs).unwrap_or_default()))
                                .filter(|(_, lit)| !lit.is_empty())
                                .collect();
                            types.insert(name, TsTypeDef::IntEnum { codes, doc: extract_doc(&e.attrs) });
                            continue;
                        }
                        WireEnumKind::Tagged(_discriminator) => {
                            // The discriminator field name is always `"type"`
                            // for the variants we care about — encoded directly
                            // in the rendered `{ type: "..." }` shape. Keep it
                            // around in case we generalize later.
                            let doc = extract_doc(&e.attrs);
                            let variants: Vec<TsEnumVariant> = e
                                .variants
                                .iter()
                                .map(|v| {
                                    let vname = v.ident.to_string();
                                    if is_wire_fallback(&v.attrs) {
                                        return TsEnumVariant::Fallback;
                                    }
                                    let wire = get_wire_attr_lit(&v.attrs).unwrap_or_default();
                                    match &v.fields {
                                        Fields::Unit => TsEnumVariant::Unit { name: vname, wire },
                                        Fields::Unnamed(unnamed) if unnamed.unnamed.len() == 1 => {
                                            let (ts, _) = rust_type_to_ts(&unnamed.unnamed[0].ty);
                                            TsEnumVariant::Tuple { name: vname, wire, inner: ts }
                                        }
                                        Fields::Unnamed(_) => TsEnumVariant::Unit { name: vname, wire },
                                        Fields::Named(named) => {
                                            let fields: Vec<TsField> = named
                                                .named
                                                .iter()
                                                .filter(|f| !has_wire_skip(&f.attrs))
                                                .map(|f| {
                                                    let fname =
                                                        f.ident.as_ref().unwrap().to_string();
                                                    let (ts, opt) = rust_type_to_ts(&f.ty);
                                                    TsField {
                                                        name: fname,
                                                        ts_type: ts,
                                                        optional: opt,
                                                        doc: extract_doc(&f.attrs),
                                                    }
                                                })
                                                .collect();
                                            TsEnumVariant::Struct { name: vname, wire, fields }
                                        }
                                    }
                                })
                                .collect();
                            types.insert(name, TsTypeDef::Enum { variants, doc });
                            continue;
                        }
                        WireEnumKind::UnitString => {
                            let doc = extract_doc(&e.attrs);
                            let mut has_fallback = false;
                            let variants: Vec<(String, String)> = e
                                .variants
                                .iter()
                                .filter_map(|v| {
                                    if is_wire_fallback(&v.attrs) {
                                        has_fallback = true;
                                        return None;
                                    }
                                    let vname = v.ident.to_string();
                                    let value = get_wire_attr_lit(&v.attrs)
                                        .unwrap_or_else(|| to_snake_case(&vname));
                                    Some((vname, value))
                                })
                                .collect();
                            types.insert(
                                name,
                                TsTypeDef::StringEnum { variants, has_fallback, doc },
                            );
                            continue;
                        }
                    }
                }

                if !has_serde_derive(&e.attrs) {
                    continue;
                }

                // Skip types that are already generated by Tsify derives in
                // result_types.rs — avoids duplicate export conflicts.
                const TSIFY_GENERATED: &[&str] = &[
                    "Event",             // WhatsAppEvent via bridge_events! macro
                    "MemberAddMode",     // Tsify enum in result_types.rs
                    "MembershipApprovalMode", // Used as bool param, not needed
                    "PresenceStatus",    // Tsify enum in result_types.rs
                    "MembershipRequest", // MembershipRequestResult in result_types.rs
                ];
                if TSIFY_GENERATED.contains(&name.as_str()) {
                    continue;
                }
                let doc = extract_doc(&e.attrs);

                // Check if all variants are unit (simple enum → string union)
                let all_unit = e.variants.iter().all(|v| matches!(v.fields, Fields::Unit));
                if all_unit {
                    let variants: Vec<(String, String)> = e
                        .variants
                        .iter()
                        .map(|v| {
                            let vname = v.ident.to_string();
                            let value = get_serde_rename_variant(v)
                                .unwrap_or_else(|| to_snake_case(&vname));
                            (vname, value)
                        })
                        .collect();
                    types.insert(
                        name,
                        TsTypeDef::StringEnum { variants, has_fallback: false, doc },
                    );
                } else {
                    // Tagged enum (serde-derived, no WireEnum)
                    let variants: Vec<TsEnumVariant> = e
                        .variants
                        .iter()
                        .map(|v| {
                            let vname = v.ident.to_string();
                            let wire = get_serde_rename_variant(v).unwrap_or_default();
                            match &v.fields {
                                Fields::Unit => TsEnumVariant::Unit { name: vname, wire },
                                Fields::Unnamed(unnamed) => {
                                    if unnamed.unnamed.len() == 1 {
                                        let (ts, _) = rust_type_to_ts(&unnamed.unnamed[0].ty);
                                        TsEnumVariant::Tuple { name: vname, wire, inner: ts }
                                    } else {
                                        TsEnumVariant::Unit { name: vname, wire }
                                    }
                                }
                                Fields::Named(named) => {
                                    let fields: Vec<TsField> = named
                                        .named
                                        .iter()
                                        .map(|f| {
                                            let fname = f.ident.as_ref().unwrap().to_string();
                                            let (ts, opt) = rust_type_to_ts(&f.ty);
                                            TsField {
                                                name: fname,
                                                ts_type: ts,
                                                optional: opt,
                                                doc: None,
                                            }
                                        })
                                        .collect();
                                    TsEnumVariant::Struct { name: vname, wire, fields }
                                }
                            }
                        })
                        .collect();
                    types.insert(name, TsTypeDef::Enum { variants, doc });
                }
            }
            _ => {}
        }
    }
}

fn has_serde_derive(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|a| {
        if !a.path().is_ident("derive") {
            return false;
        }
        let Ok(meta) = a.parse_args::<proc_macro2::TokenStream>() else {
            return false;
        };
        let s = meta.to_string();
        s.contains("Serialize") || s.contains("serde :: Serialize")
    })
}

/// Detect `#[derive(WireEnum)]` (the unified successor to `StringEnum` plus
/// hand-written `impl Serialize` blocks). Matches both `WireEnum` and
/// `crate :: WireEnum` / `wacore :: WireEnum` forms produced by `quote!`.
fn has_wire_enum_derive(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|a| {
        if !a.path().is_ident("derive") {
            return false;
        }
        let Ok(meta) = a.parse_args::<proc_macro2::TokenStream>() else {
            return false;
        };
        let s = meta.to_string();
        s.contains("WireEnum")
    })
}

#[derive(Debug)]
enum WireEnumKind {
    UnitString,
    Tagged(String),
    Int,
}

/// Inspect enum-level `#[wire(...)]` attribute to determine which mode the
/// `WireEnum` derive runs in. Mirrors `wacore_derive`'s `parse_enum_level_wire`.
fn wire_enum_kind(attrs: &[Attribute]) -> WireEnumKind {
    let mut tag_field: Option<String> = None;
    let mut int_kind = false;
    for attr in attrs {
        if !attr.path().is_ident("wire") {
            continue;
        }
        // `#[wire(tag = "type")]` and `#[wire(kind = "int")]` use parenthesized
        // nested meta. `#[wire = "..."]` uses NameValue and isn't enum-level.
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("tag") {
                if let Ok(value) = meta.value()
                    && let Ok(lit) = value.parse::<syn::LitStr>()
                {
                    tag_field = Some(lit.value());
                }
            } else if meta.path.is_ident("kind") {
                if let Ok(value) = meta.value()
                    && let Ok(lit) = value.parse::<syn::LitStr>()
                    && lit.value() == "int"
                {
                    int_kind = true;
                }
            }
            Ok(())
        });
    }
    if int_kind {
        WireEnumKind::Int
    } else if let Some(t) = tag_field {
        WireEnumKind::Tagged(t)
    } else {
        WireEnumKind::UnitString
    }
}

/// Read `#[wire = "..."]` (string mode) or `#[wire = NUM]` (int mode) from
/// a variant. Returns the literal as a string in both cases — caller decides
/// how to render. Returns `None` for variants without the attribute (e.g.
/// `#[wire_fallback]` ones).
fn get_wire_attr_lit(attrs: &[Attribute]) -> Option<String> {
    for attr in attrs {
        if !attr.path().is_ident("wire") {
            continue;
        }
        // `#[wire = "..."]` / `#[wire = 101]` — NameValue form, not parenthesized.
        if let syn::Meta::NameValue(nv) = &attr.meta
            && let syn::Expr::Lit(lit) = &nv.value
        {
            return match &lit.lit {
                syn::Lit::Str(s) => Some(s.value()),
                syn::Lit::Int(i) => Some(i.base10_digits().to_string()),
                _ => None,
            };
        }
    }
    None
}

fn is_wire_fallback(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|a| a.path().is_ident("wire_fallback"))
}

/// Field-level `#[wire(skip)]` — exclude the field from the JSON contract
/// (used for `raw: Node` payloads on `Create`/`Link`/`Unlink`).
fn has_wire_skip(attrs: &[Attribute]) -> bool {
    for attr in attrs {
        if !attr.path().is_ident("wire") {
            continue;
        }
        let mut skip = false;
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("skip") {
                skip = true;
            }
            Ok(())
        });
        if skip {
            return true;
        }
    }
    false
}

fn is_pub(vis: &syn::Visibility) -> bool {
    matches!(vis, syn::Visibility::Public(_))
}

fn extract_doc(attrs: &[Attribute]) -> Option<String> {
    let docs: Vec<String> = attrs
        .iter()
        .filter(|a| a.path().is_ident("doc"))
        .filter_map(|a| {
            if let syn::Meta::NameValue(nv) = &a.meta
                && let syn::Expr::Lit(lit) = &nv.value
                && let syn::Lit::Str(s) = &lit.lit
            {
                return Some(s.value().trim().to_string());
            }
            None
        })
        .collect();
    if docs.is_empty() {
        None
    } else {
        Some(docs.join(" "))
    }
}

fn get_serde_rename(f: &syn::Field) -> Option<String> {
    for attr in &f.attrs {
        if attr.path().is_ident("serde") {
            let Ok(meta) = attr.parse_args::<proc_macro2::TokenStream>() else {
                continue;
            };
            let s = meta.to_string();
            if let Some(pos) = s.find("rename = \"") {
                let rest = &s[pos + 10..];
                if let Some(end) = rest.find('"') {
                    return Some(rest[..end].to_string());
                }
            }
        }
    }
    None
}

fn get_serde_rename_variant(v: &syn::Variant) -> Option<String> {
    for attr in &v.attrs {
        if attr.path().is_ident("serde") {
            let Ok(meta) = attr.parse_args::<proc_macro2::TokenStream>() else {
                continue;
            };
            let s = meta.to_string();
            if let Some(pos) = s.find("rename = \"") {
                let rest = &s[pos + 10..];
                if let Some(end) = rest.find('"') {
                    return Some(rest[..end].to_string());
                }
            }
        }
    }
    None
}


/// Map a Rust type to a TypeScript type string.
/// Returns (ts_type, is_optional).
fn rust_type_to_ts(ty: &Type) -> (String, bool) {
    match ty {
        Type::Path(TypePath { path, .. }) => {
            let last = path.segments.last().unwrap();
            let ident = last.ident.to_string();

            match ident.as_str() {
                // Primitives
                "String" | "str" => ("string".to_string(), false),
                "bool" => ("boolean".to_string(), false),
                "u8" | "u16" | "u32" | "i8" | "i16" | "i32" | "f32" | "f64" => {
                    ("number".to_string(), false)
                }
                "u64" | "i64" | "u128" | "i128" | "usize" | "isize" => {
                    ("number".to_string(), false)
                }

                // Option<T> → T | null (optional field)
                "Option" => {
                    if let PathArguments::AngleBracketed(args) = &last.arguments
                        && let Some(GenericArgument::Type(inner)) = args.args.first()
                    {
                        let (inner_ts, _) = rust_type_to_ts(inner);
                        return (format!("{} | null", inner_ts), true);
                    }
                    ("any".to_string(), true)
                }

                // Vec<u8> → Uint8Array, Vec<T> → T[]
                "Vec" => {
                    if let PathArguments::AngleBracketed(args) = &last.arguments
                        && let Some(GenericArgument::Type(inner)) = args.args.first()
                    {
                        if is_u8(inner) {
                            return ("Uint8Array".to_string(), false);
                        }
                        let (inner_ts, _) = rust_type_to_ts(inner);
                        return (format!("{}[]", inner_ts), false);
                    }
                    ("any[]".to_string(), false)
                }

                // Box<T>, Arc<T>, Rc<T> → unwrap inner
                "Box" | "Arc" | "Rc" => {
                    if let PathArguments::AngleBracketed(args) = &last.arguments
                        && let Some(GenericArgument::Type(inner)) = args.args.first()
                    {
                        return rust_type_to_ts(inner);
                    }
                    ("any".to_string(), false)
                }

                // HashMap<K, V> → Record<K, V>
                "HashMap" | "BTreeMap" => {
                    if let PathArguments::AngleBracketed(args) = &last.arguments {
                        let mut iter = args.args.iter();
                        if let (Some(GenericArgument::Type(k)), Some(GenericArgument::Type(v))) =
                            (iter.next(), iter.next())
                        {
                            let (kt, _) = rust_type_to_ts(k);
                            let (vt, _) = rust_type_to_ts(v);
                            return (format!("Record<{}, {}>", kt, vt), false);
                        }
                    }
                    ("Record<string, any>".to_string(), false)
                }

                // Duration → number (milliseconds)
                "Duration" => ("number".to_string(), false),

                // DateTime → number (unix timestamp)
                "DateTime" => ("number".to_string(), false),

                // Jid → Jid (structured object with user, server, device, etc.)
                "Jid" => ("Jid".to_string(), false),

                // MessageId → string
                "MessageId" => ("string".to_string(), false),

                // MessageServerId → number
                "MessageServerId" => ("number".to_string(), false),

                // Node → any (binary protocol node)
                "Node" => ("any".to_string(), false),

                // Bytes → Uint8Array
                "Bytes" => ("Uint8Array".to_string(), false),

                // Known waproto types → any (proto types are too complex for syn)
                "Message" if path_contains_wa(path) => ("any".to_string(), false),
                "HistorySync" if path_contains_wa(path) => ("any".to_string(), false),

                // Default: use the type name as-is (assume it's another generated type)
                other => (other.to_string(), false),
            }
        }
        Type::Reference(r) => rust_type_to_ts(&r.elem),
        Type::Tuple(t) if t.elems.is_empty() => ("void".to_string(), false),
        _ => ("any".to_string(), false),
    }
}

fn is_u8(ty: &Type) -> bool {
    if let Type::Path(TypePath { path, .. }) = ty {
        path.segments.last().is_some_and(|s| s.ident == "u8")
    } else {
        false
    }
}

fn path_contains_wa(path: &syn::Path) -> bool {
    path.segments
        .iter()
        .any(|s| s.ident == "wa" || s.ident == "waproto")
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len() + 4);
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else {
            result.push(c);
        }
    }
    result
}
