//! TypeScript type generator for whatsapp-rust types.
//!
//! Parses Rust source files with `syn`, finds structs/enums with `#[derive(Serialize)]`,
//! and generates TypeScript interfaces/types.
//!
//! Usage: cargo run -p bridge-codegen > ../types/generated.d.ts

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use syn::{Attribute, Fields, GenericArgument, Item, PathArguments, Type, TypePath};
use walkdir::WalkDir;

fn main() {
    let wacore_dir = Path::new("../../whatsapp-rust/wacore/src");
    let src_dir = Path::new("../../whatsapp-rust/src");

    let mut all_types = BTreeMap::new();

    // Parse wacore types
    for entry in WalkDir::new(wacore_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "rs"))
    {
        parse_file(entry.path(), &mut all_types);
    }

    // Parse whatsapp-rust feature types
    let feature_dirs = ["features", "types"];
    for dir in feature_dirs {
        let path = src_dir.join(dir);
        if path.exists() {
            for entry in WalkDir::new(&path)
                .into_iter()
                .filter_map(|e| e.ok())
                .filter(|e| e.path().extension().is_some_and(|ext| ext == "rs"))
            {
                parse_file(entry.path(), &mut all_types);
            }
        }
    }

    // Also parse send.rs for SendOptions/RevokeType
    parse_file(&src_dir.join("send.rs"), &mut all_types);

    // Generate TypeScript
    println!("// Auto-generated from whatsapp-rust types. DO NOT EDIT.");
    println!("// Generated by: cd codegen && cargo run -p bridge-codegen");
    println!("//");
    println!("// Source: wacore/src/types/, src/features/, waproto/src/");
    println!();

    for (name, ts_type) in &all_types {
        println!("{}", ts_type.to_typescript(name));
        println!();
    }
}

#[derive(Debug)]
enum TsTypeDef {
    Interface {
        fields: Vec<TsField>,
        doc: Option<String>,
    },
    Enum {
        variants: Vec<TsEnumVariant>,
        doc: Option<String>,
    },
    StringEnum {
        variants: Vec<(String, String)>, // (name, value)
        doc: Option<String>,
    },
}

#[derive(Debug)]
struct TsField {
    name: String,
    ts_type: String,
    optional: bool,
    doc: Option<String>,
}

#[derive(Debug)]
enum TsEnumVariant {
    Unit(String),
    Tuple(String, String),          // name, inner_type
    Struct(String, Vec<TsField>),   // name, fields
}

impl TsTypeDef {
    fn to_typescript(&self, name: &str) -> String {
        match self {
            TsTypeDef::Interface { fields, doc } => {
                let mut out = String::new();
                if let Some(d) = doc {
                    out.push_str(&format!("/** {} */\n", d.trim()));
                }
                out.push_str(&format!("export interface {} {{\n", name));
                for f in fields {
                    if let Some(d) = &f.doc {
                        out.push_str(&format!("  /** {} */\n", d.trim()));
                    }
                    let opt = if f.optional { "?" } else { "" };
                    out.push_str(&format!("  {}{}: {};\n", f.name, opt, f.ts_type));
                }
                out.push_str("}");
                out
            }
            TsTypeDef::Enum { variants, doc } => {
                let mut out = String::new();
                if let Some(d) = doc {
                    out.push_str(&format!("/** {} */\n", d.trim()));
                }
                out.push_str(&format!("export type {} =\n", name));
                let parts: Vec<String> = variants
                    .iter()
                    .map(|v| match v {
                        TsEnumVariant::Unit(n) => {
                            let snake = to_snake_case(n);
                            format!("  | {{ type: \"{}\" }}", snake)
                        }
                        TsEnumVariant::Tuple(n, t) => {
                            let snake = to_snake_case(n);
                            format!("  | {{ type: \"{}\"; data: {} }}", snake, t)
                        }
                        TsEnumVariant::Struct(n, fields) => {
                            let snake = to_snake_case(n);
                            let fs: Vec<String> = fields
                                .iter()
                                .map(|f| {
                                    let opt = if f.optional { "?" } else { "" };
                                    format!("{}{}: {}", f.name, opt, f.ts_type)
                                })
                                .collect();
                            format!(
                                "  | {{ type: \"{}\"; {} }}",
                                snake,
                                fs.join("; ")
                            )
                        }
                    })
                    .collect();
                out.push_str(&parts.join("\n"));
                out.push(';');
                out
            }
            TsTypeDef::StringEnum { variants, doc } => {
                let mut out = String::new();
                if let Some(d) = doc {
                    out.push_str(&format!("/** {} */\n", d.trim()));
                }
                let parts: Vec<String> = variants
                    .iter()
                    .map(|(_, v)| format!("\"{}\"", v))
                    .collect();
                out.push_str(&format!("export type {} = {};", name, parts.join(" | ")));
                out
            }
        }
    }
}

fn parse_file(path: &Path, types: &mut BTreeMap<String, TsTypeDef>) {
    let Ok(content) = std::fs::read_to_string(path) else {
        return;
    };
    let Ok(file) = syn::parse_file(&content) else {
        return;
    };

    for item in &file.items {
        match item {
            Item::Struct(s) => {
                if has_serde_derive(&s.attrs) && is_pub(&s.vis) {
                    let name = s.ident.to_string();
                    let doc = extract_doc(&s.attrs);
                    let fields = match &s.fields {
                        Fields::Named(named) => named
                            .named
                            .iter()
                            .filter(|f| is_pub(&f.vis))
                            .map(|f| {
                                let field_name = f.ident.as_ref().unwrap().to_string().replace("r#", "");
                                let (ts_type, optional) = rust_type_to_ts(&f.ty);
                                let serde_name = get_serde_rename(f);
                                TsField {
                                    name: serde_name.unwrap_or_else(|| to_camel_case(&field_name)),
                                    ts_type,
                                    optional,
                                    doc: extract_doc(&f.attrs),
                                }
                            })
                            .collect(),
                        _ => Vec::new(),
                    };
                    if !fields.is_empty() {
                        types.insert(name, TsTypeDef::Interface { fields, doc });
                    }
                }
            }
            Item::Enum(e) => {
                if !is_pub(&e.vis) {
                    continue;
                }

                // Check if it's a StringEnum (has #[str = "..."] or #[string_default])
                if has_string_enum_derive(&e.attrs) {
                    let doc = extract_doc(&e.attrs);
                    let variants: Vec<(String, String)> = e
                        .variants
                        .iter()
                        .map(|v| {
                            let name = v.ident.to_string();
                            let value = get_str_attr(&v.attrs)
                                .unwrap_or_else(|| to_snake_case(&name));
                            (name, value)
                        })
                        .collect();
                    types.insert(
                        e.ident.to_string(),
                        TsTypeDef::StringEnum { variants, doc },
                    );
                    continue;
                }

                if !has_serde_derive(&e.attrs) {
                    continue;
                }

                let name = e.ident.to_string();
                let doc = extract_doc(&e.attrs);

                // Check if all variants are unit (simple enum → string union)
                let all_unit = e.variants.iter().all(|v| matches!(v.fields, Fields::Unit));
                if all_unit {
                    let variants: Vec<(String, String)> = e
                        .variants
                        .iter()
                        .map(|v| {
                            let vname = v.ident.to_string();
                            let value = get_serde_rename_variant(v)
                                .unwrap_or_else(|| to_snake_case(&vname));
                            (vname, value)
                        })
                        .collect();
                    types.insert(name, TsTypeDef::StringEnum { variants, doc });
                } else {
                    // Tagged enum
                    let variants: Vec<TsEnumVariant> = e
                        .variants
                        .iter()
                        .map(|v| {
                            let vname = v.ident.to_string();
                            match &v.fields {
                                Fields::Unit => TsEnumVariant::Unit(vname),
                                Fields::Unnamed(unnamed) => {
                                    if unnamed.unnamed.len() == 1 {
                                        let (ts, _) = rust_type_to_ts(&unnamed.unnamed[0].ty);
                                        TsEnumVariant::Tuple(vname, ts)
                                    } else {
                                        TsEnumVariant::Unit(vname)
                                    }
                                }
                                Fields::Named(named) => {
                                    let fields: Vec<TsField> = named
                                        .named
                                        .iter()
                                        .map(|f| {
                                            let fname = f.ident.as_ref().unwrap().to_string();
                                            let (ts, opt) = rust_type_to_ts(&f.ty);
                                            TsField {
                                                name: to_camel_case(&fname),
                                                ts_type: ts,
                                                optional: opt,
                                                doc: None,
                                            }
                                        })
                                        .collect();
                                    TsEnumVariant::Struct(vname, fields)
                                }
                            }
                        })
                        .collect();
                    types.insert(name, TsTypeDef::Enum { variants, doc });
                }
            }
            _ => {}
        }
    }
}

fn has_serde_derive(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|a| {
        if !a.path().is_ident("derive") {
            return false;
        }
        let Ok(meta) = a.parse_args::<proc_macro2::TokenStream>() else {
            return false;
        };
        let s = meta.to_string();
        s.contains("Serialize") || s.contains("serde :: Serialize")
    })
}

fn has_string_enum_derive(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|a| {
        if !a.path().is_ident("derive") {
            return false;
        }
        let Ok(meta) = a.parse_args::<proc_macro2::TokenStream>() else {
            return false;
        };
        let s = meta.to_string();
        s.contains("StringEnum")
    })
}

fn is_pub(vis: &syn::Visibility) -> bool {
    matches!(vis, syn::Visibility::Public(_))
}

fn extract_doc(attrs: &[Attribute]) -> Option<String> {
    let docs: Vec<String> = attrs
        .iter()
        .filter(|a| a.path().is_ident("doc"))
        .filter_map(|a| {
            if let syn::Meta::NameValue(nv) = &a.meta {
                if let syn::Expr::Lit(lit) = &nv.value {
                    if let syn::Lit::Str(s) = &lit.lit {
                        return Some(s.value().trim().to_string());
                    }
                }
            }
            None
        })
        .collect();
    if docs.is_empty() {
        None
    } else {
        Some(docs.join(" "))
    }
}

fn get_serde_rename(f: &syn::Field) -> Option<String> {
    for attr in &f.attrs {
        if attr.path().is_ident("serde") {
            let Ok(meta) = attr.parse_args::<proc_macro2::TokenStream>() else {
                continue;
            };
            let s = meta.to_string();
            if let Some(pos) = s.find("rename = \"") {
                let rest = &s[pos + 10..];
                if let Some(end) = rest.find('"') {
                    return Some(rest[..end].to_string());
                }
            }
        }
    }
    None
}

fn get_serde_rename_variant(v: &syn::Variant) -> Option<String> {
    for attr in &v.attrs {
        if attr.path().is_ident("serde") {
            let Ok(meta) = attr.parse_args::<proc_macro2::TokenStream>() else {
                continue;
            };
            let s = meta.to_string();
            if let Some(pos) = s.find("rename = \"") {
                let rest = &s[pos + 10..];
                if let Some(end) = rest.find('"') {
                    return Some(rest[..end].to_string());
                }
            }
        }
    }
    None
}

fn get_str_attr(attrs: &[Attribute]) -> Option<String> {
    for attr in attrs {
        if attr.path().is_ident("str") {
            let Ok(meta) = attr.parse_args::<proc_macro2::TokenStream>() else {
                continue;
            };
            let s = meta.to_string();
            // Parse: "value"
            if let Some(start) = s.find('"') {
                let rest = &s[start + 1..];
                if let Some(end) = rest.find('"') {
                    return Some(rest[..end].to_string());
                }
            }
        }
    }
    None
}

/// Map a Rust type to a TypeScript type string.
/// Returns (ts_type, is_optional).
fn rust_type_to_ts(ty: &Type) -> (String, bool) {
    match ty {
        Type::Path(TypePath { path, .. }) => {
            let last = path.segments.last().unwrap();
            let ident = last.ident.to_string();

            match ident.as_str() {
                // Primitives
                "String" | "str" => ("string".to_string(), false),
                "bool" => ("boolean".to_string(), false),
                "u8" | "u16" | "u32" | "i8" | "i16" | "i32" | "f32" | "f64" => {
                    ("number".to_string(), false)
                }
                "u64" | "i64" | "u128" | "i128" | "usize" | "isize" => {
                    ("number".to_string(), false)
                }

                // Option<T> → T | null (optional field)
                "Option" => {
                    if let PathArguments::AngleBracketed(args) = &last.arguments {
                        if let Some(GenericArgument::Type(inner)) = args.args.first() {
                            let (inner_ts, _) = rust_type_to_ts(inner);
                            return (format!("{} | null", inner_ts), true);
                        }
                    }
                    ("any".to_string(), true)
                }

                // Vec<u8> → Uint8Array, Vec<T> → T[]
                "Vec" => {
                    if let PathArguments::AngleBracketed(args) = &last.arguments {
                        if let Some(GenericArgument::Type(inner)) = args.args.first() {
                            if is_u8(inner) {
                                return ("Uint8Array".to_string(), false);
                            }
                            let (inner_ts, _) = rust_type_to_ts(inner);
                            return (format!("{}[]", inner_ts), false);
                        }
                    }
                    ("any[]".to_string(), false)
                }

                // Box<T>, Arc<T>, Rc<T> → unwrap inner
                "Box" | "Arc" | "Rc" => {
                    if let PathArguments::AngleBracketed(args) = &last.arguments {
                        if let Some(GenericArgument::Type(inner)) = args.args.first() {
                            return rust_type_to_ts(inner);
                        }
                    }
                    ("any".to_string(), false)
                }

                // HashMap<K, V> → Record<K, V>
                "HashMap" | "BTreeMap" => {
                    if let PathArguments::AngleBracketed(args) = &last.arguments {
                        let mut iter = args.args.iter();
                        if let (
                            Some(GenericArgument::Type(k)),
                            Some(GenericArgument::Type(v)),
                        ) = (iter.next(), iter.next())
                        {
                            let (kt, _) = rust_type_to_ts(k);
                            let (vt, _) = rust_type_to_ts(v);
                            return (format!("Record<{}, {}>", kt, vt), false);
                        }
                    }
                    ("Record<string, any>".to_string(), false)
                }

                // Duration → number (milliseconds)
                "Duration" => ("number".to_string(), false),

                // DateTime → number (unix timestamp)
                "DateTime" => ("number".to_string(), false),

                // Jid → string
                "Jid" => ("string".to_string(), false),

                // MessageId → string
                "MessageId" => ("string".to_string(), false),

                // MessageServerId → number
                "MessageServerId" => ("number".to_string(), false),

                // Node → any (binary protocol node)
                "Node" => ("any".to_string(), false),

                // Bytes → Uint8Array
                "Bytes" => ("Uint8Array".to_string(), false),

                // Known waproto types → any (proto types are too complex for syn)
                "Message" if path_contains_wa(path) => ("any".to_string(), false),
                "HistorySync" if path_contains_wa(path) => ("any".to_string(), false),

                // Default: use the type name as-is (assume it's another generated type)
                other => (other.to_string(), false),
            }
        }
        Type::Reference(r) => rust_type_to_ts(&r.elem),
        Type::Tuple(t) if t.elems.is_empty() => ("void".to_string(), false),
        _ => ("any".to_string(), false),
    }
}

fn is_u8(ty: &Type) -> bool {
    if let Type::Path(TypePath { path, .. }) = ty {
        path.segments.last().is_some_and(|s| s.ident == "u8")
    } else {
        false
    }
}

fn path_contains_wa(path: &syn::Path) -> bool {
    path.segments
        .iter()
        .any(|s| s.ident == "wa" || s.ident == "waproto")
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    let mut capitalize_next = false;
    for (i, c) in s.chars().enumerate() {
        if c == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(c.to_ascii_uppercase());
            capitalize_next = false;
        } else if i == 0 {
            result.push(c);
        } else {
            result.push(c);
        }
    }
    result
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len() + 4);
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        } else {
            result.push(c);
        }
    }
    result
}
