// Auto-generated from whatsapp-rust types. DO NOT EDIT.
// Generated by: cd codegen && cargo run -p bridge-codegen
//
// Source: wacore/src/types/, src/features/, waproto/src/

/** Addressing mode for a group (phone number vs LID). */
export type AddressingMode = "pn" | "lid";

/** App state synchronization key for WhatsApp's app state protocol. */
export interface AppStateSyncKey {
  keyData: Uint8Array;
  fingerprint: Uint8Array;
  timestamp: number;
}

export interface ArchiveUpdate {
  jid: string;
  timestamp: number;
  action: ArchiveChatAction;
  fromFullSync: boolean;
}

/** Action to perform on a blocklist entry. */
export type BlocklistAction = "block" | "unblock";

export type BotEditType = "first" | "inner" | "last";

/** Parsed `<notification type="business">` stanza. */
export interface BusinessNotification {
  from: string;
  stanzaId: string;
  timestamp: number;
  notificationType: BusinessNotificationType;
  jid?: string | null;
  hash?: string | null;
  verifiedName?: VerifiedName | null;
  productIds: string[];
  collectionIds: string[];
  subscriptions: BusinessSubscription[];
}

/** Business notification type based on child element. */
export type BusinessNotificationType = "remove_jid" | "remove_hash" | "verified_name_jid" | "verified_name_hash" | "profile" | "profile_hash" | "product" | "collection" | "subscriptions" | "unknown";

/** Business status update notification. */
export interface BusinessStatusUpdate {
  jid: string;
  updateType: BusinessUpdateType;
  timestamp: number;
  targetJid?: string | null;
  hash?: string | null;
  verifiedName?: string | null;
  productIds: string[];
  collectionIds: string[];
  subscriptions: BusinessSubscription[];
}

/** Business subscription information (SMB features). */
export interface BusinessSubscription {
  id: string;
  status: string;
  expirationDate?: number | null;
  creationTime?: number | null;
}

/** Type of business status update. */
export type BusinessUpdateType = "removed_as_business" | "verified_name_changed" | "profile_updated" | "products_updated" | "collections_updated" | "subscriptions_updated" | "unknown";

export interface Category {
  id: string;
  name: string;
}

export type ChatPresence = "composing" | "paused";

export type ChatPresenceMedia = "" | "audio";

export interface ChatPresenceUpdate {
  source: MessageSource;
  state: ChatPresence;
  media: ChatPresenceMedia;
}

/** Chat state type for typing indicators. */
export type ChatStateType = "composing" | "recording" | "paused";

export interface ConnectFailure {
  reason: ConnectFailureReason;
  message: string;
  raw?: any | null;
}

export type ConnectFailureReason =
  | { type: "generic" }
  | { type: "logged_out" }
  | { type: "temp_banned" }
  | { type: "main_device_gone" }
  | { type: "unknown_logout" }
  | { type: "client_outdated" }
  | { type: "bad_user_agent" }
  | { type: "cat_expired" }
  | { type: "cat_invalid" }
  | { type: "not_found" }
  | { type: "client_unknown" }
  | { type: "internal_server_error" }
  | { type: "experimental" }
  | { type: "service_unavailable" }
  | { type: "unknown"; data: number };

/** A contact changed their phone number.  Emitted from `<notification type="contacts"><modify old="..." new="..." old_lid="..." new_lid="..."/>`.  WA Web creates two LID-PN mappings (`old_lid→old_jid`, `new_lid→new_jid`) and generates a system notification message in both old and new chats. */
export interface ContactNumberChanged {
  /** Old phone number JID. */
  oldJid: string;
  /** New phone number JID. */
  newJid: string;
  /** Old LID (if provided by server). */
  oldLid?: string | null;
  /** New LID (if provided by server). */
  newLid?: string | null;
  timestamp: number;
}

/** Server requests a full contact re-sync.  Emitted from `<notification type="contacts"><sync after="..."/>`. */
export interface ContactSyncRequested {
  after?: number | null;
  timestamp: number;
}

export interface ContactUpdate {
  jid: string;
  timestamp: number;
  action: ContactAction;
  fromFullSync: boolean;
}

/** A contact's profile changed (server notification).  Emitted from `<notification type="contacts"><update jid="..."/>`. WA Web resets cached presence and refreshes the profile picture on this event — consumers should invalidate any cached presence/profile data.  Not to be confused with [`ContactUpdate`] which comes from app-state sync mutations (different source, different payload). */
export interface ContactUpdated {
  jid: string;
  timestamp: number;
}

export type DecryptFailMode = "show" | "hide";

export interface Device {
  pn?: string | null;
  lid?: string | null;
  registrationId: number;
  noiseKey: KeyPair;
  identityKey: KeyPair;
  signedPreKey: KeyPair;
  signedPreKeyId: number;
  signedPreKeySignature: any;
  advSecretKey: any;
  account?: AdvSignedDeviceIdentity | null;
  pushName: string;
  appVersionPrimary: number;
  appVersionSecondary: number;
  appVersionTertiary: number;
  appVersionLastFetchedMs: number;
  deviceProps: DeviceProps;
  /** Edge routing info received from server, used for optimized reconnection. When present, this should be sent as a pre-intro before the Noise handshake. */
  edgeRoutingInfo?: Uint8Array | null;
  /** Hash from the last props (A/B experiment config) fetch. Sent on subsequent connects to enable delta updates instead of full fetches. */
  propsHash?: string | null;
  /** Monotonically increasing counter for one-time pre-key ID generation. Matches WhatsApp Web's `NEXT_PK_ID` pattern: only increases, never resets. Prevents prekey ID collisions when prekeys are consumed non-sequentially. */
  nextPreKeyId: number;
}

/** Device element from notification.  Wire format: ```xml <device jid="185169143189667:75@lid" key-index="2" lid="..."/> ```  Device ID is extracted from the JID's device part (e.g., 75 from "user:75@lid").  Per WhatsApp Web: if both `jid` and `lid` attributes are present, the device IDs must match or the notification is rejected. */
export interface DeviceElement {
  /** Device JID (contains user and device ID) */
  jid: string;
  /** Optional key index */
  keyIndex?: number | null;
  /** Optional LID (device ID must match jid's device ID if present) */
  lid?: string | null;
}

/** Device information for registry tracking. */
export interface DeviceInfo {
  /** The device ID (0 = primary device, 1+ = companion devices) */
  deviceId: number;
  /** The key index, if known */
  keyIndex?: number | null;
}

/** Device list record matching WhatsApp Web's DeviceListRecord structure. */
export interface DeviceListRecord {
  /** The user part of the JID (phone number or LID) */
  user: string;
  /** List of known devices for this user */
  devices: DeviceInfo[];
  /** Timestamp when this record was last updated */
  timestamp: number;
  /** Participant hash from usync, if available */
  phash?: string | null;
}

/** Device list update notification. Emitted when a user's device list changes (device added/removed/updated). */
export interface DeviceListUpdate {
  /** The user whose device list changed (from attribute) */
  user: string;
  /** Optional LID user (for LID-PN mapping) */
  lidUser?: string | null;
  /** Type of update (add/remove/update) */
  updateType: DeviceListUpdateType;
  /** Affected devices with detailed info */
  devices: DeviceNotificationInfo[];
  /** Key index info (for add/remove) */
  keyIndex?: KeyIndexInfo | null;
  /** Contact hash (for update - used for contact lookup) */
  contactHash?: string | null;
}

/** Type of device list update notification. Matches WhatsApp Web's device notification types. */
export type DeviceListUpdateType = "add" | "remove" | "update";

/** Parsed device notification stanza.  Wire format: ```xml <notification from="185169143189667@lid" id="..." t="..." type="devices" lid="..."> <remove> <device jid="185169143189667:75@lid"/> <key-index-list ts="1769296600"/> </remove> </notification> ```  Reference: WhatsApp Web `WAWebHandleDeviceNotification` parser (5Yec01dI04o.js:23125-23183)  Per WhatsApp Web: Only ONE operation per notification is processed. Priority order: remove > add > update */
export interface DeviceNotification {
  /** User JID (from attribute) */
  from: string;
  /** Optional LID user (for LID-PN mapping learning) */
  lidUser?: string | null;
  /** Stanza ID (for ACK) */
  stanzaId: string;
  /** Timestamp */
  timestamp: number;
  /** The operation (one per notification, priority: remove > add > update) */
  operation: DeviceOperation;
}

/** Device information from notification. */
export interface DeviceNotificationInfo {
  /** Device ID (extracted from JID) */
  deviceId: number;
  /** Optional key index */
  keyIndex?: number | null;
}

/** Device notification operation type.  Wire format: Child element tag of `<notification type="devices">` - `<add>` - Device was added - `<remove>` - Device was removed - `<update>` - Device info updated (hash-based lookup) */
export type DeviceNotificationType = "add" | "remove" | "update";

/** Operation content (add/remove/update child element).  Wire format per WhatsApp Web (5Yec01dI04o.js:23141-23180): ```xml <add> <device jid="user:75@lid" key-index="2"/> <key-index-list ts="...">SIGNED_BYTES</key-index-list> </add> <!-- OR --> <remove> <device jid="user:75@lid"/> <key-index-list ts="..."/>  <!-- ts required for remove --> </remove> <!-- OR --> <update hash="CONTACT_HASH"/> ```  Note: WhatsApp Web does NOT read any attributes from add/remove nodes. The `device_hash` attribute (if present) is not used by the official client. */
export interface DeviceOperation {
  /** Operation type (add/remove/update) */
  operationType: DeviceNotificationType;
  /** Contact hash (for update only) - from `hash` attribute, used for contact lookup */
  contactHash?: string | null;
  /** Device elements (for add/remove, single device per WhatsApp Web) */
  devices: DeviceElement[];
  /** Key index info (required for add/remove per WhatsApp Web) */
  keyIndex?: KeyIndexInfo | null;
}

export interface DeviceSentMeta {
  destinationJid: string;
  phash: string;
}

/** Known dirty bit types. */
export type DirtyType = "account_sync" | "groups" | "other";

/** A contact's default disappearing messages setting changed.  Sent by the server as `<notification type="disappearing_mode">`. WA Web: `WAWebHandleDisappearingModeNotification` → `WAWebUpdateDisappearingModeForContact`. */
export interface DisappearingModeChanged {
  /** The contact whose setting changed. */
  from: string;
  /** New duration in seconds (0 = disabled, 86400 = 24h, etc.). */
  duration: number;
  /** Unix timestamp (seconds) when the setting was changed. Consumers should only apply this if it's newer than their stored timestamp. */
  settingTimestamp: number;
}

export type EditAttribute = "empty" | "message_edit" | "pin_in_chat" | "admin_edit" | "sender_revoke" | "admin_revoke" | "unknown";

export type Event =
  | { type: "connected"; data: Connected }
  | { type: "disconnected"; data: Disconnected }
  | { type: "pair_success"; data: PairSuccess }
  | { type: "pair_error"; data: PairError }
  | { type: "logged_out"; data: LoggedOut }
  | { type: "pairing_qr_code"; code: string; timeout: number }
  | { type: "pairing_code"; code: string; timeout: number }
  | { type: "qr_scanned_without_multidevice"; data: QrScannedWithoutMultidevice }
  | { type: "client_outdated"; data: ClientOutdated }
  | { type: "message" }
  | { type: "receipt"; data: Receipt }
  | { type: "undecryptable_message"; data: UndecryptableMessage }
  | { type: "notification"; data: any }
  | { type: "chat_presence"; data: ChatPresenceUpdate }
  | { type: "presence"; data: PresenceUpdate }
  | { type: "picture_update"; data: PictureUpdate }
  | { type: "user_about_update"; data: UserAboutUpdate }
  | { type: "contact_updated"; data: ContactUpdated }
  | { type: "contact_number_changed"; data: ContactNumberChanged }
  | { type: "contact_sync_requested"; data: ContactSyncRequested }
  | { type: "joined_group"; data: LazyConversation }
  | { type: "group_update"; data: GroupUpdate }
  | { type: "contact_update"; data: ContactUpdate }
  | { type: "push_name_update"; data: PushNameUpdate }
  | { type: "self_push_name_updated"; data: SelfPushNameUpdated }
  | { type: "pin_update"; data: PinUpdate }
  | { type: "mute_update"; data: MuteUpdate }
  | { type: "archive_update"; data: ArchiveUpdate }
  | { type: "star_update"; data: StarUpdate }
  | { type: "mark_chat_as_read_update"; data: MarkChatAsReadUpdate }
  | { type: "history_sync"; data: HistorySync }
  | { type: "offline_sync_preview"; data: OfflineSyncPreview }
  | { type: "offline_sync_completed"; data: OfflineSyncCompleted }
  | { type: "device_list_update"; data: DeviceListUpdate }
  | { type: "business_status_update"; data: BusinessStatusUpdate }
  | { type: "stream_replaced"; data: StreamReplaced }
  | { type: "temporary_ban"; data: TemporaryBan }
  | { type: "connect_failure"; data: ConnectFailure }
  | { type: "stream_error"; data: StreamError }
  | { type: "disappearing_mode_changed"; data: DisappearingModeChanged }
  | { type: "newsletter_live_update"; data: NewsletterLiveUpdate };

export interface GroupInfo {
  participants: string[];
  addressingMode: AddressingMode;
}

/** All possible group notification action types.  Maps 1:1 to `GROUP_NOTIFICATION_TAG` child element tags from WhatsApp Web. */
export type GroupNotificationAction =
  | { type: "add"; participants: GroupParticipantInfo[]; reason?: string | null }
  | { type: "remove"; participants: GroupParticipantInfo[]; reason?: string | null }
  | { type: "promote"; participants: GroupParticipantInfo[] }
  | { type: "demote"; participants: GroupParticipantInfo[] }
  | { type: "modify"; participants: GroupParticipantInfo[] }
  | { type: "subject"; subject: string; subjectOwner?: string | null; subjectTime?: number | null }
  | { type: "description"; id: string; description?: string | null }
  | { type: "locked"; threshold?: string | null }
  | { type: "unlocked" }
  | { type: "announce" }
  | { type: "not_announce" }
  | { type: "ephemeral"; expiration: number; trigger?: number | null }
  | { type: "membership_approval_mode"; enabled: boolean }
  | { type: "member_add_mode"; mode: string }
  | { type: "no_frequently_forwarded" }
  | { type: "frequently_forwarded_ok" }
  | { type: "invite"; code: string }
  | { type: "revoke_invite" }
  | { type: "growth_locked"; expiration: number; lockType: string }
  | { type: "growth_unlocked" }
  | { type: "create"; raw: any }
  | { type: "delete"; reason?: string | null }
  | { type: "link"; linkType: string; raw: any }
  | { type: "unlink"; unlinkType: string; unlinkReason?: string | null; raw: any }
  | { type: "unknown"; tag: string };

/** Participant info extracted from `<participant>` child elements.  Wire format: ```xml <participant jid="1234567890@s.whatsapp.net" phone_number="1234567890@s.whatsapp.net"/> ``` */
export interface GroupParticipantInfo {
  jid: string;
  phoneNumber?: string | null;
}

/** Query request type. */
export type GroupQueryRequestType = "interactive";

/** Group update notification.  Emitted for each action in a `<notification type="w:gp2">` stanza. A single notification may produce multiple `GroupUpdate` events (one per action). */
export interface GroupUpdate {
  /** The group this update applies to */
  groupJid: string;
  /** The admin/user who triggered the change (`participant` attribute) */
  participant?: string | null;
  /** Phone number JID of the participant (for LID-addressed groups) */
  participantPn?: string | null;
  /** When the change occurred */
  timestamp: number;
  /** Whether the group uses LID addressing mode */
  isLidAddressingMode: boolean;
  /** The specific action */
  action: GroupNotificationAction;
}

/** IQ request type for WhatsApp protocol queries. */
export type InfoQueryType = "set" | "get";

/** Key index information from `<key-index-list>` element.  Wire format: ```xml <!-- For add: has signed bytes content --> <key-index-list ts="1769296600">SIGNED_BYTES</key-index-list> <!-- For remove: empty, ts required --> <key-index-list ts="1769296600"/> ```  Required for add/remove operations per WhatsApp Web. */
export interface KeyIndexInfo {
  /** Timestamp (required for remove per WhatsApp Web) */
  timestamp: number;
  /** Signed key index bytes (only present for add) */
  signedBytes?: Uint8Array | null;
}

/** The source from which a LID-PN mapping was learned. Different sources have different trust levels and handling for identity changes. */
export type LearningSource = "usync" | "peer_pn_message" | "peer_lid_message" | "recipient_latest_lid" | "migration_sync_latest" | "migration_sync_old" | "blocklist_active" | "blocklist_inactive" | "pairing" | "device_notification" | "other";

/** An entry in the LID-PN cache containing the full mapping information. */
export interface LidPnEntry {
  /** The LID user part (e.g., "100000012345678") */
  lid: string;
  /** The phone number user part (e.g., "559980000001") */
  phoneNumber: string;
  /** Unix timestamp when the mapping was first learned */
  createdAt: number;
  /** The source from which this mapping was learned */
  learningSource: LearningSource;
}

/** Entry representing a LID to Phone Number mapping. */
export interface LidPnMappingEntry {
  /** The LID user part (e.g., "100000012345678") */
  lid: string;
  /** The phone number user part (e.g., "559980000001") */
  phoneNumber: string;
  /** Unix timestamp when the mapping was first learned */
  createdAt: number;
  /** Unix timestamp when the mapping was last updated */
  updatedAt: number;
  /** The source from which this mapping was learned (e.g., "usync", "peer_pn_message") */
  learningSource: string;
}

export interface LoggedOut {
  onConnect: boolean;
  reason: ConnectFailureReason;
}

export interface MarkChatAsReadUpdate {
  jid: string;
  timestamp: number;
  action: MarkChatAsReadAction;
  fromFullSync: boolean;
}

/** Member add mode for who can add participants. */
export type MemberAddMode = "admin_add" | "all_member_add";

/** Member link mode for group invite links. */
export type MemberLinkMode = "admin_link" | "all_member_link";

/** Membership approval mode for join requests. */
export type MembershipApprovalMode = "off" | "on";

export interface MessageInfo {
  source: MessageSource;
  id: string;
  serverId: number;
  type: string;
  pushName: string;
  timestamp: number;
  category: string;
  multicast: boolean;
  mediaType: string;
  edit: EditAttribute;
  botInfo?: MsgBotInfo | null;
  metaInfo: MsgMetaInfo;
  verifiedName?: VerifiedNameCertificate | null;
  deviceSentMeta?: DeviceSentMeta | null;
}

export interface MessageSource {
  chat: string;
  sender: string;
  isFromMe: boolean;
  isGroup: boolean;
  addressingMode?: AddressingMode | null;
  senderAlt?: string | null;
  recipientAlt?: string | null;
  broadcastListOwner?: string | null;
  recipient?: string | null;
}

/** MEX GraphQL error extensions. */
export interface MexErrorExtensions {
  errorCode?: number | null;
  isSummary?: boolean | null;
  isRetryable?: boolean | null;
  severity?: string | null;
}

/** MEX GraphQL error. */
export interface MexGraphQLError {
  message: string;
  extensions?: MexErrorExtensions | null;
}

/** MEX GraphQL response. */
export interface MexResponse {
  data?: Value | null;
  errors?: MexGraphQLError[] | null;
}

export interface MsgBotInfo {
  editType?: BotEditType | null;
  editTargetId?: string | null;
  editSenderTimestampMs?: number | null;
}

export interface MsgMetaInfo {
  targetId?: string | null;
  targetSender?: string | null;
  deprecatedLidSession?: boolean | null;
  threadMessageId?: string | null;
  threadMessageSenderJid?: string | null;
}

export interface MuteUpdate {
  jid: string;
  timestamp: number;
  action: MuteAction;
  fromFullSync: boolean;
}

/** A newsletter live update notification, typically containing updated reaction counts for one or more messages. */
export interface NewsletterLiveUpdate {
  newsletterJid: string;
  messages: NewsletterLiveUpdateMessage[];
}

/** A single message entry in a newsletter live update. */
export interface NewsletterLiveUpdateMessage {
  serverId: number;
  reactions: NewsletterLiveUpdateReaction[];
}

/** A reaction count in a newsletter live update. */
export interface NewsletterLiveUpdateReaction {
  code: string;
  count: number;
}

export interface OfflineSyncCompleted {
  count: number;
}

export interface OfflineSyncPreview {
  total: number;
  appDataChanges: number;
  messages: number;
  notifications: number;
  receipts: number;
}

export interface PairError {
  id: string;
  lid: string;
  businessName: string;
  platform: string;
  error: string;
}

export interface PairSuccess {
  id: string;
  lid: string;
  businessName: string;
  platform: string;
}

/** Participant type (admin level). */
export type ParticipantType = "member" | "admin" | "super_admin";

export interface PictureUpdate {
  /** The JID whose picture changed (user or group). */
  jid: string;
  /** The user who made the change. Present for group picture changes (the admin who changed it). `None` for personal picture updates. */
  author?: string | null;
  timestamp: number;
  /** Whether the picture was removed (true) or set/updated (false). */
  removed: boolean;
  /** The server-assigned picture ID (from `<set id="..."/>`). `None` for deletions. */
  pictureId?: string | null;
}

export interface PinUpdate {
  jid: string;
  timestamp: number;
  action: PinAction;
  fromFullSync: boolean;
}

/** Platform identifiers for companion devices. These match the DeviceProps.PlatformType protobuf enum. */
export type PlatformId = "unknown" | "chrome" | "firefox" | "internet_explorer" | "opera" | "safari" | "edge" | "electron" | "uwp" | "other_web_client";

export type Presence = "available" | "unavailable";

/** Presence status for online/offline state. */
export type PresenceStatus = "available" | "unavailable";

export interface PresenceUpdate {
  from: string;
  unavailable: boolean;
  lastSeen?: number | null;
}

/** Privacy setting category name. */
export type PrivacyCategory = "last" | "online" | "profile" | "status" | "group_add" | "read_receipts" | "other";

export type PrivacySetting = "all" | "contacts" | "contact_blacklist" | "match_last_seen" | "known" | "none" | "undefined";

export type PrivacySettingType = "group_add" | "last" | "status" | "profile" | "read_receipts" | "online" | "call_add";

export interface PrivacySettings {
  groupAdd?: PrivacySetting | null;
  lastSeen?: PrivacySetting | null;
  status?: PrivacySetting | null;
  profile?: PrivacySetting | null;
  readReceipts?: PrivacySetting | null;
  callAdd?: PrivacySetting | null;
  online?: PrivacySetting | null;
}

/** Privacy setting value. */
export type PrivacyValue = "all" | "contacts" | "none" | "contact_blacklist" | "match_last_seen" | "other";

/** Profile picture type (preview thumbnail or full-size). */
export type ProfilePictureType = "preview" | "full";

export interface PushNameUpdate {
  jid: string;
  message: MessageInfo;
  oldPushName: string;
  newPushName: string;
}

export interface Receipt {
  source: MessageSource;
  messageIds: string[];
  timestamp: number;
  type: ReceiptType;
  messageSender: string;
}

export type ReceiptType =
  | { type: "delivered" }
  | { type: "sender" }
  | { type: "retry" }
  | { type: "enc_rekey_retry" }
  | { type: "read" }
  | { type: "read_self" }
  | { type: "played" }
  | { type: "played_self" }
  | { type: "server_error" }
  | { type: "inactive" }
  | { type: "peer_msg" }
  | { type: "history_sync" }
  | { type: "other"; data: string };

/** Chat state type as received from incoming stanzas.  Aligned with WhatsApp Web's `WAChatState` constants: - `typing` = ACTIVE_CHAT_STATE_TYPE.TYPING - `recording_audio` = ACTIVE_CHAT_STATE_TYPE.RECORDING_AUDIO - `idle` = IDLE_CHAT_STATE_TYPE.IDLE */
export type ReceivedChatState = "typing" | "recording_audio" | "idle";

export interface SelfPushNameUpdated {
  fromServer: boolean;
  oldName: string;
  newName: string;
}

/** The type of spam flow indicating the source of the report. */
export type SpamFlow = "group_spam_banner_report" | "group_info_report" | "message_menu" | "contact_info" | "status_report";

/** Unique identifier for a message stanza within a chat. Used for deduplication and retry tracking. */
export interface StanzaKey {
  chat: string;
  id: string;
}

export interface StarUpdate {
  chatJid: string;
  /** The participant who sent the message. `Some` for group messages from others, `None` for self-authored or 1-on-1 messages (wire value `"0"`). */
  participantJid?: string | null;
  messageId: string;
  fromMe: boolean;
  timestamp: number;
  action: StarAction;
  fromFullSync: boolean;
}

/** Privacy setting sent in the `<meta>` node of the status stanza. Matches WhatsApp Web's `status_setting` attribute. */
export type StatusPrivacySetting = "contacts" | "allow_list" | "deny_list";

export interface StreamError {
  code: string;
  raw?: any | null;
}

/** Trusted contact privacy token entry.  Matches WhatsApp Web's Chat.tcToken / tcTokenTimestamp / tcTokenSenderTimestamp. */
export interface TcTokenEntry {
  /** Raw token bytes received from the server. */
  token: Uint8Array;
  /** Unix timestamp (seconds) when the token was received. */
  tokenTimestamp: number;
  /** Unix timestamp (seconds) when we last issued our token to this contact. */
  senderTimestamp?: number | null;
}

export type TempBanReason =
  | { type: "sent_to_too_many_people" }
  | { type: "blocked_by_users" }
  | { type: "created_too_many_groups" }
  | { type: "sent_too_many_same_message" }
  | { type: "broadcast_list" }
  | { type: "unknown"; data: number };

export interface TemporaryBan {
  code: TempBanReason;
  expire: number;
}

export type UnavailableType = "unknown" | "view_once";

export interface UndecryptableMessage {
  info: MessageInfo;
  isUnavailable: boolean;
  unavailableType: UnavailableType;
  decryptFailMode: DecryptFailMode;
}

export interface UserAboutUpdate {
  jid: string;
  status: string;
  timestamp: number;
}

/** Usync context. */
export type UsyncContext = "interactive" | "background" | "message";

/** Usync mode. */
export type UsyncMode = "query" | "full";

/** Verified name certificate information. */
export interface VerifiedName {
  name?: string | null;
  serial?: string | null;
  issuer?: string | null;
  certificate?: Uint8Array | null;
}

