// TypeScript type definitions are automatically generated by napi-rs from Rust code.
// The types below document the public API for the JavaScript layer.

// For napi-rs, TypeScript definitions are automatically generated from struct definitions
// with #[napi(object)] and function signatures with #[napi].
//
// The main types are:
// - WasmNode: Represents a decoded binary node (from wasm_api.rs)
// - EncryptResult: Represents the output of Signal protocol encryption (from libsignal_api.rs)
//
// All exported functions are defined in wasm_api.rs and libsignal_api.rs
// and will be automatically available in the generated TypeScript declarations.
